Output example.gif

Set FontSize 24
Set Width 1200
Set Height 600

Type "# What language to choose for a project?" Sleep 500ms Enter
Type "anyra pick go java python cobol" Sleep 500ms Enter
Sleep 2s

Enter Enter

Type "# In what order to implement features?" Sleep 500ms Enter
Type 'anyra shuffle "Pizza ordering" Authentication "Dice rolling"' Sleep 500ms Enter
Sleep 2s

Enter Enter

Type "# How long will it take?" Sleep 500ms Enter
Type "anyra roll 2d20 + d10 + 3" Sleep 500ms Enter

Sleep 3s
